const works = [
  { id: '', title: '' },
  { id: '2ugrqyDeoY0', title: "넬(NELL) 'Sweet Delusion' Official MV" },
  { id: 'LVw93DLIE78', title: "n.SSign(엔싸인) - 'Funky like me (Feat. PEAK & PITCH)' MV" },
  { id: 'LU06eFKen9k', title: "ARrC (아크) 'SKIID' MV" },
  { id: '5xzE2JtYIq0', title: "온앤오프(ONF) 'Put It Back' MV" },
  { id: 'NGV2vnOx2Ps', title: "NMIXX(엔믹스) 'SPINNIN ON IT' Performance Video" },
  { id: 'ZhQfdombNuI', title: "SNH48GROUP 《终极殿堂》MV" },
  { id: 'V9iN-Yj0VTI', title: "위아이(WEi) 'HOME' M/V" },
  { id: 'xLsufOSKMq0', title: "NuNew - Leave Me With Your Love I OFFICIAL MV" },
  { id: 'Qr7svLd9lcE', title: "신승훈 (SHIN SEUNG HUN) - She Was MV" },
  { id: 'ycTEdhDFVDI', title: "ARrC (아크) 'vitamin I' Pharmacy Room Live Session" },
  { id: '4TTI8UR7kTE', title: "8TURN(에잇턴) 'Electric Heart' M/V" },
  { id: 'gjHcbWTXqEY', title: "VIVIZ (비비지) - 'La La Love Me' MV" },
  { id: 'LTDTQtF2n00', title: "n.SSign(엔싸인) - 'Itty Bitty' MV" },
  { id: 'SUmiSDKKsv8', title: "[MV] JEONG DONG WON(정동원) _ Heung!(흥!) (Feat. HAON(김하온))" },
  { id: 'yBBJS-R0wcI', title: "Suzy - 간절한 소원 (Waiting On A Wish) (백설공주 OST)" },
  { id: 'Evj4Qq8F1mQ', title: "ONEWE(원위) '별 헤는 밤 (The Starry Night)' MV" },
  { id: 'YmnQ0CUQWf4', title: "ARrC (아크) 'loop.dll' Performance Video" },
  { id: '0kBL7n_Yxak', title: "A2O MAY 'B.B.B (Bigger Badder Better)' Official Video" },
  { id: 'z-xfGoabprU', title: "STAYC(스테이씨) 'BEBE' MV" },
  { id: '2LcTlKpq9GY', title: "1st FanCon 1,2 QWER l Concert VCR (Opening, Bridge)" },
  { id: 'zyv3yLIr1WM', title: "[NouerA] 무한대 (無限大) Performance Video" },
  { id: 'Kdubj6Rr-wE', title: "Nayeon - 저 너머로 (Beyond) (모아나 2 OST) ft. Te Vaka" },
  { id: '7R2MGUIz1sM', title: "SMORZ - 'I want you to' Official M/V" },
  { id: '_NxTvO6DBKQ', title: "퍼플키스(PURPLE KISS) 'ON MY BIKE' MV" },
  { id: 'Ezd-Qm7gZYs', title: "SNH48 GROUP 《最好的朋友》MV" },
  { id: 'FlqHSi64UVM', title: "BEWAVE(비웨이브) '너에게로 가는 길이 너무 어려워' MV" },
  { id: 'UTEiMqmaldo', title: "[M/V] 'Weekend' | 드리핀(DRIPPIN)" },
  { id: 'JGqSEM9-LWM', title: "BE'O (비오) - 'Criminal (Feat. MC몽)' MV" },
  { id: '7snm8wnfTmI', title: "로시(Rothy) - 'Happy End' Official MV" },
  { id: 'S87cPr_hZks', title: "82MAJOR(82메이저) '촉(Choke)' Performance" },
  { id: 'ef8SZV6yfIQ', title: "[MV] 솔라 (Solar) 'But I'" },
  { id: 'FkefRSxpuFk', title: "규빈 (Gyubin) - Really Like You [Music Video]" },
  { id: 'pwzF5Du7lQA', title: "미래소년 (MIRAE) - RUNNING UP (Kor Ver.)" },
  { id: 'N68rwFjyinI', title: "[MV] SOYEON of (G)I-DLE X WINTER of aespa X LIZ of IVE 'NOBODY'" },
  { id: 'B6sXFzD-sww', title: "潘瑋柏 Will Pan《狂愛 MAD LOVE》Official Music Video" },
  { id: 'rR0pZgfav4I', title: "넬(NELL) 'Moon Shower' Official MV" },
  { id: '5cOEjnG-nhI', title: 'YAOCHEN- "Adventure Player" M/V' },
  { id: 'cUdOOxQBqx8', title: "로시(Rothy) - '너의 계절이 돌아올 거야' Official MV" },
  { id: 'RknLOnO6ZtI', title: "Billlie | 'DANG! (hocus pocus)' M/V" },
  { id: 'Inkr9_3arto', title: "폴킴 (Paul Kim) '화 좀 풀어봐' | MV" },
  { id: 'OxFUC866Tk0', title: "2023 SNH48 GROUP 《Number One》MV" },
  { id: 'jZ6-luSZybE', title: "로시(Rothy) - 'Something Casual' Official MV" },
  { id: 'gPo-G0cSy-0', title: "뷔(V) 'Slow Dancing' Band Session" },
  { id: 'r2rZXrsBAfE', title: "뷔(V) 'Love Me Again' Band Session" },
  { id: 'x2En2r0Pzns', title: "넬(NELL) 'Wanderer' Official MV" },
  { id: 'k7KkaPKmFIQ', title: "aespa 에스파 'Better Things' The Performance Stage" },
  { id: 'hb73cGFLzKk', title: "aespa 에스파 'Better Things' Performance Video" },
  { id: '1BROMl-k28k', title: 'BOY STORY "Z.I.P (Zero Is the only Passion)" M/V' },
  { id: 'TojVe_CYHjk', title: "YESUNG '束の間の恋' MV" },
  { id: '3MN2yjzoVK0', title: "LE'V(레비) [A.I.BAE] MV (Korean Ver.)" },
  { id: '5U9_FjHELnY', title: "박지훈(PARK JIHOON) 'Blank Effect (무표정)' Official M/V" },
  { id: 'a7d5aFNh-YE', title: "Billlie - GingaMingaYo (the strange world) - Japanese ver." },
  { id: 'Pi4bGTUw3tI', title: "김재환 (KIM JAE HWAN) - 봄바람 (Spring Breeze) official MV" },
  { id: 'dK7a9rDgU3g', title: "YESUNG 예성 'Floral Sense (Feat. 윈터 of aespa)' MV" },
  { id: 'Qc7_zRjH808', title: "FIFTY FIFTY (피프티피프티) - 'Cupid' Official MV" },
  { id: 'WFqGKa6p1V8', title: "퍼플키스(PURPLE KISS) 'Sweet Juice' MV" },
  { id: '4y-jbO8mGP0', title: "Agust D 'People Pt.2 (feat. IU)' Live Clip | SUGA: Road to D-DAY" },
  { id: 'PLSQhFxBsas', title: "Agust D 'People' Live Clip | SUGA: Road to D-DAY" },
  { id: 'kj2YpzJkDco', title: "Golden Child 日本 3rd Single invisible Crayon Music Video" },
  { id: '69IT-53ULZA', title: "&TEAM 'Scent of you' Official MV" },
  { id: 'ZDG5rSDvl1Y', title: "[OFFICIAL MV] 이승윤 '웃어주었어'" },
  { id: '4-mrl36Eo5c', title: "9001 (Ninety O One) - 마네퀸 Mannequin Official M/V" },
  { id: 'jpZF2zW38TE', title: "[MV] 마마무 - 하나,둘,셋 어이! (1,2,3 Eoi!)" },
  { id: 'Vz508O9NNTg', title: "[MV] 마마무 (MAMAMOO) - ILLELLA (일낼라)" },
  { id: 'Kad9ieYMF4Y', title: "미래소년 (MIRAE) - Drip N' Drop" },
  { id: 'z8Eu-HU0sWQ', title: "Billlie | 'RING ma Bell (what a wonderful world)' M/V" },
  { id: 'H6EpRSkTPg4', title: "Billlie | the end of the world and the awakening | chapter two" },
  { id: 'yTVp04RwUxo', title: "[MV] KWON EUN BI(권은비) - LIGHT (KPOP CTzen OST)" },
  { id: 'wKYCOlLxY8Q', title: "FTISLAND - DOOR OFFICIAL MUSIC VIDEO" },
  { id: 'b0qMefc2RdY', title: "CNBLUE - LET IT SHINE Official Music Video" },
  { id: 'ueJR9ZqUJmg', title: "[track by YOON] Billlie, 윤종신 '팥빙수' M/V" },
  { id: 'I02ULETFESI', title: "SUPER JUNIOR 슈퍼주니어 'Mango' MV" },
  { id: 'SPYX2y4NzTU', title: '[MV] 이달의 소녀 (LOONA) "Flip That"' },
  { id: 'sMG9t39BwUU', title: "KARD - Ring The Alarm _ M/V" },
  { id: 'dTX-6WdiXx8', title: "Rocket Punch Japan 1st Single Fiore M/V" },
  { id: 'S1K06BmGm_o', title: "LE SSERAFIM (르세라핌) 'FEARLESS' @ CDTV LIVE! LIVE!" },
  { id: '9ixJZM_4EKg', title: "CHOA(초아) 'Yesterday' Official MV" },
  { id: 'uGJoFdgE6ts', title: "MV | 나훈아(Na Hoon-A) - Change(체인지) | 일곱 빛 향기" },
  { id: 'YKKh8d4wZbU', title: "Billlie | 'GingaMingaYo (the strange world)' M/V" },
  { id: 'U82kuwN0PlE', title: "Billlie | what is your B? | the collective soul and unconscious: chapter one" },
];
